name: Node CI

on:
  push:
    branches: [development, staging, master]
  pull_request:
    branches: [development, staging, master]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm i -g yarn
      - name: Install app dependencies
        run: yarn
        env:
          CI: true
      - name: Eslint
        run: yarn lint
      - name: Tests
        run: yarn test
        env:
          SKIP_PREFLIGHT_CHECK: true
      - name: Build production
        run: yarn build-cd
        env:
          SKIP_PREFLIGHT_CHECK: true